---
title: Projekt BoardBase
subtitle: Sprawozdanie z Etapu 1 - Zaawansowane systemy baz danych
format:
  pdf:
    output-file: Etap 1 Sprawozdanie Krzysztof Dąbrowski 293101.pdf
    toc: true
    lof: true
    lot: true
    # fig-pos: 'H'
---

{{< include ../shared/repo_callout.qmd >}}

# Zmiany w diagramie ERD

Poprawiłem diagram \acr{ERD} @fig-erd, odnosząc się do uwag do _Case Study_. Wprowadziłem następujące zmiany:

- Usunąłem tablice słownikowe zastępując je bezpośrednimi atrybutami w tabelach,
- Usunąłem tabele _Collection_ tworząc bezpośrednią relację N:N między _User_ a _GameRelease_. Niestety straciłem w ten sposób informacje o nazwie kolekcji, ale nie wiem jak to rozwiązać,
- Dodałem tablicę _Location_, do monitorowania gdzie miały miejsce rozgrywki.
- Dodałem tablicę _Price_, pozwalającą śledzić ceny danego wydania. Tabela zawiera datę startu i końca obowiązywania ceny, żebyś śledzić jej zmiany w czasie,
- Dodałem tabelę _Award_, aby móc przechowywać informacje o nagrodach zdobytych przez gry planszowe.

```{mermaid}
%%| fig-align: left
%%| label: fig-erd
%%| fig-cap: Zaktualizowany diagram ERD
%%| file: ERD.mmd
%%| fig-width: 6
%%| fig-height: 8.5
```

# Utworzenie bazy danych

Wybrałem \acr{SZBD} PostgreSQL. Opis mojego wyboru i konfiguracji \acr{SZBD} przedstawiłem w [Case Study](https://github.com/christopher-dabrowski/BoardBase/blob/main/docs/case-study/CaseStudy.qmd).

Sama baza danych `boardbase` została utworzona automatycznie na podstawie konfiguracji kontenera Docker. \
Przed utworzeniem tabel utworzyłem schemat bazodanowy `mian` z autoryzacją dla domyślnego użytkownika `postgres` zgodnie z dokumentacją @postgres-docs:createschema.

Po stworzeniu pierwszych tabl w schemacie `main` zauważyłem, że pisząc zapytania muszę nazwy razem ze schematem. Zastanowiło mnie to, ponieważ w przeszłości wykonywałem zapytania w innych bazach danych podając samą nazwę tabeli. Przeczytałem więcej dokumentacji @postgres-docs:ddl-schemas na temat działania schematów w PostgreSQL i znalazłem informację, że można skonfigurować domyślnie przeszukiwane schematy. \
Dowiedziałem się, że rekomendowaną praktyką jest dodanie schematu do domyślnego wyszukiwania, tak więc zrobiłem.


# Źródła {.unnumbered}

::: {#refs}
:::
