erDiagram
    GAME {
        string gameName
    }
    CATEGORY {
        string categoryName
    }
    RATING {
        int enjoyment
        int minimalPlayerCount
        int maximumPlayerCount
        int minimalAge
        int complexity
        timestamp date
    }
    USER {
        string username
        string email
        boolean isAdmin
        binary passwordHash
    }

    USER ||--o{ RATING : "gives"
    GAME ||--o{ RATING : "receives"

    %% USER ||--o{ REVIEW : "writes"
    %% GAME ||--o{ REVIEW : "is reviewed in"

    %% USER ||--|| COLLECTION : "owns"
    %% COLLECTION }o--o{ GAME : "contains"

    %% USER ||--|| WISHLIST : "has"
    %% WISHLIST }o--o{ GAME : "includes"

    GAME }o--o{ CATEGORY : "belongs to category"

    GAME }o--o{ MECHANIC : "uses"
