client.allow_telemetry=false

server.memory.heap.initial_size=2g
server.memory.heap.max_size=2g
server.memory.pagecache.size=512m

server.jvm.additional=-XX:+ExitOnOutOfMemoryError

server.default_listen_address=0.0.0.0
server.directories.logs=/logs
